# Generated by Django 3.2.5 on 2021-07-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='upload_title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
